version: "3.7"
services:
  front:
    build:
      context: ./front
    depends_on:
      - "rabbitmq"
    ports:
      - 8080:8080
    command: node front.js
    networks:
      - rabbitmq_nodejs

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    expose:
      - 5672
    ports:
      - 15673:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_nodejs
  relacje:
    build:
      context: ./relacje
      target: dev
    depends_on:
      - "rabbitmq"
    expose:
      - 5000
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node relacje.js'
    environment:
      NODE_ENV: production
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - rabbitmq_nodejs

networks:
  rabbitmq_nodejs:
    driver: bridge
